# Copyright 2024 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later
- name: Deploy the Raspberry Pi of my Taichung home
  hosts: all
  handlers:
    - name: >-
        Reload the avahi-daemon service to apply configuration changes
      become: true
      ansible.builtin.service:
        name: avahi-daemon
        state: reloaded

    - name: Reboot system to apply changes
      become: true
      ansible.builtin.reboot:

    - name: >-
        Start Fail2ban service again if the Debian 12 workaround is
        applied
      become: true
      ansible.builtin.service:
        name: fail2ban
        state: started

  tasks:
    - name: Update installed packages to its latest versions, to avoid fixed bugs
      become: true
      ansible.builtin.package:
        name: '*'
        # This is a full-system deployment playbook
        # noqa package-latest
        state: latest

    - name: Check whether reboot is required after update
      when: ansible_os_family == "Debian"
      register: apt_reboot_is_required_raw
      changed_when: apt_reboot_is_required_raw.stat.exists
      notify: Reboot system to apply changes
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: false

    - name: Enable broadcasting the host's existence via Zeroconf
      become: true
      notify: >-
        Reload the avahi-daemon service to apply configuration changes
      ansible.builtin.replace:
        path: /etc/avahi/avahi-daemon.conf
        regexp: '^publish-workstation=no'
        replace: 'publish-workstation=yes'

    - name: Deploy WireGuard
      become: true
      ansible.builtin.import_role:
        name: githubixx.ansible_role_wireguard

    - name: Deploy Fail2ban to avoid SSH brute-force attacks
      become: true
      ansible.builtin.package:
        name: fail2ban

    - name: >-
        Workaround fail2ban/fail2ban#3292 on Debian 12 so that F2B
        service can be started
      when: >-
        ansible_os_family == "Debian"
        and ansible_distribution_major_version == "12"
      become: true
      notify: >-
        Start Fail2ban service again if the Debian 12 workaround is
        applied
      ansible.builtin.lineinfile:
        path: /etc/fail2ban/jail.d/defaults-debian.conf
        regexp: '^backend = '
        insertafter: '^\[sshd\]$'
        line: backend = systemd
